### ISSUE TITLE
Only works if display is set to Display Group "Default"

### ISSUE THREAD

**Issue by sberl** [htool/signalk-bandg-displaydaynight#1]
I had my instruments set to display group 1, and they did not respond. Changing the display group to "default" got things going. 
I would be nice if the display group was a configurable parameter of the plugin. That way when an installation has multiple groups it could work.
Bonus points if it allowed multiple display groups with different parameters. For example displays at the nav station vs displays in the cockpit.

**Comment by htool** [comment]
Network Group selection can now be done.
Multiple groups not yet, that's a bigger overhaul.

**Comment by htool** [comment]
Multiple groups was easier than expected. That's now in as well.

**Comment by sberl** [comment]
Very nice. Thank you. Will try it out soon.
